In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("/kaggle/input/competitions/titanic/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [37]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [38]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
print(df["Age"].dtype)
print(df["Age"].isnull().mean()*100)
print(df["Age"].nunique())

float64
19.865319865319865
88

In [41]:
print(df["Cabin"].dtype)
print(df["Cabin"].isnull().mean()*100)
print(df["Cabin"].nunique())

object
77.10437710437711
147

In [42]:
print(df["Embarked"].dtype)
print(df["Embarked"].isnull().mean()*100)
print(df["Embarked"].nunique())

object
0.22446689113355783
3

In [43]:
print(df["Age"].skew())

0.38910778230082704

In [44]:
mean_age = df["Age"].mean()
print(mean_age)
df["Age"] = df["Age"].fillna(mean_age)

29.69911764705882

In [45]:
df["Age"].isnull().sum()

np.int64(0)

In [46]:
df = df.drop("Cabin", axis = 1)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [48]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [49]:
df["Embarked"] = df["Embarked"].fillna("S")

In [50]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [51]:
df["SibSp"].value_counts()

SibSp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [52]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [53]:
df["Ticket"].value_counts()

Ticket
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1
Name: count, Length: 681, dtype: int64

In [54]:
df["Name"].value_counts()

Name
Dooley, Mr. Patrick                                    1
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
                                                      ..
Hewlett, Mrs. (Mary D Kingcome)                        1
Vestrom, Miss. Hulda Amanda Adolfina                   1
Andersson, Mr. Anders Johan                            1
Saundercock, Mr. William Henry                         1
Bonnell, Miss. Elizabeth                               1
Name: count, Length: 891, dtype: int64

In [55]:
df["Name"].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [56]:
df['extracted_text'] = df['Name'].str.extract(r',\s*(.*?)\s*\.')
df["extracted_text"].value_counts()

extracted_text
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [57]:
counts = df['extracted_text'].map(df['extracted_text'].value_counts())
df['extracted_text'] = df['extracted_text'].mask(counts < 40 , 'Other')

In [58]:
df["extracted_text"].value_counts()

extracted_text
Mr        517
Miss      182
Mrs       125
Master     40
Other      27
Name: count, dtype: int64

In [59]:
df = df.drop("Name", axis=1)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     891 non-null    int64
 1   Survived        891 non-null    int64
 2   Pclass          891 non-null    int64
 3   Sex             891 non-null    object
 4   Age             891 non-null    float64
 5   SibSp           891 non-null    int64
 6   Parch           891 non-null    int64
 7   Ticket          891 non-null    object
 8   Fare            891 non-null    float64
 9   Embarked        891 non-null    object
 10  extracted_text  891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [61]:
df["Ticket"].head(15)

0            A/5 21171
1             PC 17599
2     STON/O2. 3101282
3               113803
4               373450
5               330877
6                17463
7               349909
8               347742
9               237736
10             PP 9549
11              113783
12           A/5. 2151
13              347082
14              350406
Name: Ticket, dtype: object

In [62]:
print(df["Ticket"].value_counts())
df['Ticket_Group_Size'] = df['Ticket'].map(df['Ticket'].value_counts())

Ticket
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1
Name: count, Length: 681, dtype: int64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PassengerId        891 non-null    int64
 1   Survived           891 non-null    int64
 2   Pclass             891 non-null    int64
 3   Sex                891 non-null    object
 4   Age                891 non-null    float64
 5   SibSp              891 non-null    int64
 6   Parch              891 non-null    int64
 7   Ticket             891 non-null    object
 8   Fare               891 non-null    float64
 9   Embarked           891 non-null    object
 10  extracted_text     891 non-null    object
 11  Ticket_Group_Size  891 non-null    int64
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB

In [64]:
df = df.drop("PassengerId", axis=1)

In [65]:
numerical_features = [
    "Pclass","Age","SibSp","Parch",
    "Fare", "Ticket_Group_Size"
]
categorical_features = [
    "Sex",
    "Embarked","extracted_text"
]

In [71]:
X = df[["Pclass","Age","SibSp","Parch",
    "Fare", "Ticket_Group_Size","Sex",
    "Embarked","extracted_text"]]
y = df["Survived"]

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [74]:
print(X_train)

     Pclass        Age  SibSp  Parch      Fare  Ticket_Group_Size     Sex  \
692       3  29.699118      0      0   56.4958                  7    male
481       2  29.699118      0      0    0.0000                  1    male
527       1  29.699118      0      0  221.7792                  1    male
855       3  18.000000      0      1    9.3500                  1  female
801       2  31.000000      1      1   26.2500                  3  female
..      ...        ...    ...    ...       ...                ...     ...
359       3  29.699118      0      0    7.8792                  1  female
258       1  35.000000      0      0  512.3292                  3  female
736       3  48.000000      1      3   34.3750                  4  female
462       1  47.000000      0      0   38.5000                  1    male
507       1  29.699118      0      0   26.5500                  1    male

    Embarked extracted_text
692        S             Mr
481        S             Mr
527        S             Mr
855        S            Mrs
801        S            Mrs
..       ...            ...
359        Q           Miss
258        C           Miss
736        S            Mrs
462        S             Mr
507        S             Mr

[712 rows x 9 columns]

In [75]:
print(X_test)

     Pclass        Age  SibSp  Parch     Fare  Ticket_Group_Size     Sex  \
565       3  24.000000      2      0  24.1500                  2    male
160       3  44.000000      0      1  16.1000                  1    male
553       3  22.000000      0      0   7.2250                  1    male
860       3  41.000000      2      0  14.1083                  1    male
241       3  29.699118      1      0  15.5000                  2  female
..      ...        ...    ...    ...      ...                ...     ...
880       2  25.000000      0      1  26.0000                  2  female
91        3  20.000000      0      0   7.8542                  1    male
883       2  28.000000      0      0  10.5000                  1    male
473       2  23.000000      0      0  13.7917                  1  female
637       2  31.000000      1      1  26.2500                  3    male

    Embarked extracted_text
565        S             Mr
160        S             Mr
553        C             Mr
860        S             Mr
241        Q           Miss
..       ...            ...
880        S            Mrs
91         S             Mr
883        S             Mr
473        C            Mrs
637        S             Mr

[179 rows x 9 columns]

In [76]:
print(y_train)

692    1
481    0
527    0
855    1
801    1
      ..
359    1
258    1
736    0
462    0
507    1
Name: Survived, Length: 712, dtype: int64

In [77]:
print(y_test)

565    0
160    0
553    1
860    0
241    1
      ..
880    1
91     0
883    0
473    1
637    0
Name: Survived, Length: 179, dtype: int64